# -*- coding: utf-8 -*-
"""Calc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUiS7GU-_6F3Ng9Qq4Ga-32XsQGWSUyj
"""

def add(x,y):
  '''Takes two input and return a added value of the passed input'''
  return x+y

def sub(x,y):
  '''Takes two input and return a subtract value of the passed input'''
  return x-y

def prod(x,y):
  '''Takes two input and return a Product value of the passed input'''
  return x*y

def div(x,y):
  '''Takes two input and return a division value of the passed input'''
  return x/y